# -*- coding: utf-8 -*-
"""binary_hex_converter.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fnGc2BiEXWPFgAo90oo9xYTbJwCiMu_A
"""

def decimal_to_binary(n):
  binary = [0] * 8
  power = 7

  while n > 0:
    if n >= 2 ** power:
      binary[7 - power] = 1
      n -= 2 ** power
    power -= 1

  return ''.join(map(str, binary))


def binary_to_hex(binary_str):
  hex_map = {
      "0000": "0", "0001": "1", "0010": "2", "0011": "3",
      "0100": "4", "0101": "5", "0110": "6", "0111": "7",
      "1000": "8", "1001": "9", "1010": "A", "1011": "B",
      "1100": "C", "1101": "D", "1110": "E", "1111": "F"
  }
  return hex_map[binary_str[:4]] + hex_map[binary_str[4:]]


def main():
  while True:
    try:
      dec = int(input("請輸入 0-255 的數字: "))
      if 0 <= dec <= 255:
        binary = decimal_to_binary(dec)
        hex_value = binary_to_hex(binary)
        print(f"十進位: {dec} -> 二進位: {binary} -> 十六進位: {hex_value}")
      else:
        print("請輸入 0 到 255 之間的數字。")
    except ValueError:
      print("請輸入有效的整數！")

if __name__ == "__main__":
  main()